// AUTO-GENERATED by vite plugin. Do not edit.
import type app from './server'

export type PageName = 'About' | 'Home' | 'Posts/Index' | 'Posts/New' | 'Posts/Show'

declare module '../src/page-props' {
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '../src/page-props'
