import { readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, relative, resolve } from 'node:path'
import type { Plugin } from 'vite'

type Options = {
  pagesDir?: string
  outFile?: string
  exclude?: string[]
}

export function inertiaPagesPlugin(options: Options = {}): Plugin {
  const cwd = process.cwd()
  const root = resolve(cwd, options.pagesDir ?? 'app/pages')
  const out = resolve(cwd, options.outFile ?? 'app/pages.gen.ts')
  const exclude = new Set(options.exclude ?? ['Layout'])

  const collect = () => {
    const pages: string[] = []
    const walk = (dir: string) => {
      for (const entry of readdirSync(dir)) {
        const full = join(dir, entry)
        if (statSync(full).isDirectory()) {
          walk(full)
        } else if (entry.endsWith('.tsx')) {
          const name = relative(root, full)
            .replace(/\.tsx$/, '')
            .replaceAll('\\', '/')
          if (!exclude.has(name)) pages.push(name)
        }
      }
    }
    walk(root)
    return pages.sort()
  }

  const generate = () => {
    const pages = collect()
    const union = pages.length ? pages.map((p) => `'${p}'`).join(' | ') : 'never'
    writeFileSync(
      out,
      `// AUTO-GENERATED by vite plugin. Do not edit.
import type app from './server'

export type PageName = ${union}

declare module '../src/page-props' {
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '../src/page-props'
`
    )
  }

  return {
    name: 'inertia-pages',
    buildStart: generate,
    configureServer(server) {
      generate()
      const onChange = (file: string) =>
        file.startsWith(root) && file.endsWith('.tsx') && generate()
      server.watcher.on('add', onChange)
      server.watcher.on('unlink', onChange)
    }
  }
}
